### PR TITLE
week2

### PR DESCRIPTION
**Pull request by millie0808**
Discord username：millie000
[http://52.74.27.178:3000/](http://52.74.27.178:3000/)

Thank you!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We have to implement **scrolling effect** on MRT list.
2. Main frame of content should keep 1200px width in any devices where screen width>1200px.

**Comment by millie0808** [comment]
I have addressed the issues. Thank you!

**Comment by cwpeng** [comment]
Re-request review so that I can review for you.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
